Module5-Demo1/Models/MessageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Module5_Demo1.Models
{
    public class MessageViewModel
    {
        public int MyProperty1 { get; set; }
        public string MyProperty2 { get; set; }
    }
}

Module5-Demo1/Models/Personne.cs
using Module5_Demo1.ValidationAttributs;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Module5_Demo1.Models
{
    public class Personne
    {
        public int Id { get; set; }

        [Required]
        //[Compare("Prenom")]
        //[Phone]
        //[RegularExpression("")]
        [MyValidationAttribut("B")]
        public string Nom { get; set; }

        [StringLength(20, MinimumLength = 5)]
        [EmailAddress] // a@a.a
        public string Prenom { get; set; }

        [Range(5, 105)]
        public int Age { get; set; }
    }
}

Module5-Demo1/Models/PersonneViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Module5_Demo1.Models
{
    public class PersonneViewModel
    {
        public int? Id { get; set; }
        public int? Age { get; set; }

        public Personne Personne { get; set; }
    }
}

Module5-Demo1/Controllers/DemoController.cs
using Module5_Demo1.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Module5_Demo1.Controllers
{
    public class DemoController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Mon message";
            Debug.Write(TempData["key2"]);

            MessageViewModel vm = new MessageViewModel() { MyProperty1 = 10, MyProperty2 = "welcome from vm" };

            return View(vm);
        }

        public ActionResult Test1()
        {
            TempData["key1"] = "valeur de key1";

            return View();
        }

        public ActionResult Test2()
        {
            TempData["key2"] = "valeur de key2";

            return RedirectToAction("Index");
        }
    }
}

Module5-Demo1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Module5_Demo1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Module5-Demo1/Controllers/PersonneController.cs
using Module5_Demo1.Models;
using Module5_Demo1.Utils;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Module5_Demo1.Controllers
{
    public class PersonneController : Controller
    {
        // GET: Personne
        public ActionResult Index()
        {
            return View(FakeDb.Instance.Personnes);
        }

        // GET: Personne/Details/5
        public ActionResult Details(int id)
        {
            return View(FakeDb.Instance.Personnes.FirstOrDefault(x => x.Id == id));
        }

        // GET: Personne/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Personne/Create
        [HttpPost]
        public ActionResult Create(Personne personne)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    FakeDb.Instance.Personnes.Add(personne);
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("key1", "mon message d'erreur");
                    return View(personne);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Personne/Edit/5
        public ActionResult Edit(int id)
        {
            PersonneViewModel vm = new PersonneViewModel();
            vm.Personne = FakeDb.Instance.Personnes.FirstOrDefault(x => x.Id == id);
            vm.Id = vm.Personne.Id;
            vm.Age = vm.Personne.Age;

            return View(vm);
        }

        // POST: Personne/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, PersonneViewModel vm)
        {
            //Debug.WriteLine(this.HttpContext);
            try
            {
                Personne toUpdate = FakeDb.Instance.Personnes.FirstOrDefault(x => x.Id == id);
                toUpdate.Nom = vm.Personne.Nom;
                toUpdate.Prenom = vm.Personne.Prenom;
                if (vm.Age.HasValue)
                {
                    toUpdate.Age = vm.Age.Value;
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Personne/Delete/5
        public ActionResult Delete(int id)
        {
            return View(FakeDb.Instance.Personnes.FirstOrDefault(x => x.Id == id));
        }

        // POST: Personne/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                FakeDb.Instance.Personnes.Remove(FakeDb.Instance.Personnes.FirstOrDefault(x => x.Id == id));

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Module5-Demo1/Views/Demo/Index.cshtml
@model Module5_Demo1.Models.MessageViewModel

@{ ViewBag.Title = "Index"; }

<h2>Index</h2>

<p>@ViewBag.Message</p>
<p>@TempData["key2"]</p>

<p>@Model.MyProperty1 @Model.MyProperty2</p>

Module5-Demo1/Views/Demo/Test1.cshtml
@{ ViewBag.Title = "Test1"; }

<h2>Test1</h2>

<p>@TempData["key1"]</p>

Module5-Demo1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Personnes", "Index", "Personne")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>